### ISSUE TITLE
Remove mimetype and glob based filetype

### ISSUE THREAD

**Issue by rentzso** [scitran/api#137]

**Comment by kofalt** [comment]
Could you elaborate?
Is this talking about the removal of glob-based type determining of incoming files?

I ask mainly because, at least currently, the [job match rules](https://github.com/scitran/api/blob/cb581d1ba8f484a7110cd9d62425c7b79c7c43bd/api/rules.py#L38-L57) still depend on the `file.type` being provided on incoming data. Meanwhile the niftis are still a file glob.

Does this affect that at all? Or will the connector still be providing that information?

**Comment by gsfr** [comment]
@kofalt: Not to worry. This is just removing an interim hack, now that the reaper and gears are providing `file.type` for all incoming files. (@dpuccetti-flywheel, @mrDarcyMurphy, @elisapoquette: The UI should eventually do the same for all user uploads, but that may not be a bali requirement.) This will also remove all instances of the legacy `file.filetype` and `file.mimetype`.

@all: All team members should permanently cache the [data model](https://github.com/scitran/api/wiki/Data-Model) to memory and adhere to it at all times.
